export default {
    name: "Reza Souri",
    home: "HOME",
    about: "ABOUT",
    resume: "RESUME",
    portfolios: "PORTFOLIOS",
    contact: "CONTACT",
    hi1: "Hi, I am ",
    hi2: "",
    desc: "I am a frontend web developer.I can provide clean code and pixel perfect design.I also make website more & more interactive with web animations.",
    aboutme: "ABOUT ME",
    services: "SERVICES",
    fullname: "Full Name",
    age: "AGE",
    nationality: "Nationality",
    languages: "Languages",
    phone: "Phone",
    years: "Years",
    iranian: "Iranian",
    persian: "Persian",
    english: "English",
    downloadcv: "DOWNLOAD CV",
    webdesign: "Web Design",
    webdevelopement: "Web Development",
    mobileapplication: "Mobile Application",
    servicedesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem tenetur ratione quod.",
    myskills: "MY SKILLS",
    workingSteps: [
        { id: -2, date: "", title: "", subtitle: "", content: "" },
        { id: 0, date: "2018-2019", title: "Frontend Web Developer", subtitle: "Abc University", content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, magni mollitia, aspernatur consequatur accusamus vero eum facere exercitationem velit suscipit ipsam placeat libero. Deleniti exercitationem nostrum quasi. Molestiae, vel porro." },
        { id: 1, date: "2018-2019", title: "Backend Web Developer", subtitle: "Abc University", content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, magni mollitia, aspernatur consequatur accusamus vero eum facere exercitationem velit suscipit ipsam placeat libero. Deleniti exercitationem nostrum quasi. Molestiae, vel porro." },
        { id: -3, date: "", title: "", subtitle: "", content: "" }
    ],
    educationalSteps: [
        { id: -2, date: "", title: "", subtitle: "", content: "" },
        { id: 0, date: "2018-2019", title: "Master of Science", subtitle: "Abc University", content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, magni mollitia, aspernatur consequatur accusamus vero eum facere exercitationem velit suscipit ipsam placeat libero. Deleniti exercitationem nostrum quasi. Molestiae, vel porro." },
        { id: 1, date: "2018-2019", title: "Bachelor of Science", subtitle: "Abc University", content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, magni mollitia, aspernatur consequatur accusamus vero eum facere exercitationem velit suscipit ipsam placeat libero. Deleniti exercitationem nostrum quasi. Molestiae, vel porro." },
        { id: 2, date: "2018-2019", title: "High School Education", subtitle: "Abc University", content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, magni mollitia, aspernatur consequatur accusamus vero eum facere exercitationem velit suscipit ipsam placeat libero. Deleniti exercitationem nostrum quasi. Molestiae, vel porro." },
        { id: -3, date: "", title: "", subtitle: "", content: "" }
    ],
    workingexperience: "Working Experience",
    educationalqualifications: "Educational Qualifications",
    contactme:"CONTACT ME",
    getintouch:"Get In Touch",
    enteryourname:"Enter your name",
    enteryouremail:"Enter your email",
    enteryoursubject:"Enter your subject",
    enteryourmessage:"Enter your Message",
    sendmail:"SEND MAIL",
    email:"Email",
    address:"Address",
    adstreet:"121 King Street, Melbourne, Victoria 3000, Australia",
    portfoliosList : [
        { id: 1, title: "react developer", image: "https://api.reactdeveloper.ir/storage/course-images/JauFkTD9652YzLtW5YbjUjvuNXRWihW4eoIVSLwf.png", desc: "react teacher" },
        { id: 2, title: "react native", image: "https://api.reactdeveloper.ir/storage/course-images/JauFkTD9652YzLtW5YbjUjvuNXRWihW4eoIVSLwf.png", desc: "react edu" },
        { id: 3, title: "android developer", image: "https://api.reactdeveloper.ir/storage/course-images/JauFkTD9652YzLtW5YbjUjvuNXRWihW4eoIVSLwf.png", desc: "react pycharm" },
        { id: 4, title: "node developer", image: "https://api.reactdeveloper.ir/storage/course-images/JauFkTD9652YzLtW5YbjUjvuNXRWihW4eoIVSLwf.png", desc: "react dom" },
        { id: 5, title: "pyton developer", image: "https://api.reactdeveloper.ir/storage/course-images/JauFkTD9652YzLtW5YbjUjvuNXRWihW4eoIVSLwf.png", desc: "react teacher" },
        { id: 6, title: "ml developer", image: "https://api.reactdeveloper.ir/storage/course-images/JauFkTD9652YzLtW5YbjUjvuNXRWihW4eoIVSLwf.png", desc: "react teacher" },
    ]
}